name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.4]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Test Dependencies
        shell: bash
        run: poetry run python test_dependencies.py

      - name: Test
        run: |
          poetry run python manage.py test
        env:
          DEBUG: 1
          SECRET_KEY: django-insecure-sycypm_*o2g*eez5cyd1dst&5thgp*+z0^l7kl-v(#s*l5xsme
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: bookstore_dev_db
          SQL_USER: bookstore_dev
          SQL_PASSWORD: bookstore_dev
          SQL_HOST: db
          SQL_PORT: 5432
