name: Python application

on: [push]

jobs:
  build:
    environment: secrets
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.2.0]

    env:
      DEBUG: ${{secrets.DEBUG}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DJANGO_ALLOWED_HOSTS: ${{secrets.SQL_DJANGO_ALLOWED_HOSTS}}
      SQL_ENGINE: ${{secrets.SQL_ENGINE}}
      SQL_DATABASE: ${{secrets.SQL_DATABASE}}
      SQL_USER: ${{secrets.SQL_USER}}
      SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_HOST: ${{secrets.SQL_HOST}}
      SQL_PORT: ${{secrets.SQL_PORT}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Test
        run: |
          poetry run python manage.py test
